import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "login - ByCourse",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
        {children}
    </div>
  );
}