import type { Metadata } from "next";
import Navbar from "@/components/dashboard-component/navbar";

export const metadata: Metadata = {
  title: "dasboard - ByCourse",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <Navbar />
        {children}
    </div>
  );
}